CREATE DATABASE IF NOT EXISTS INTRANET DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE INTRANET;



DROP TABLE IF EXISTS PROFS;
CREATE TABLE IF NOT EXISTS PROFS(
  id_prof int(11) AUTO_INCREMENT,
  nom_prof VARCHAR(20),
  prenom_prof VARCHAR(20),
  matiere_cours VARCHAR(25),
  loginProf VARCHAR(20),
  PRIMARY KEY (id_prof)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS ETUDIANTS;
CREATE TABLE IF NOT EXISTS ETUDIANTS(
  id_etudiant int(11) AUTO_INCREMENT,
  nom_etudiant VARCHAR(20),
  prenom_etudiant VARCHAR(20),
  loginEtudiant VARCHAR(20),
  PRIMARY KEY (id_etudiant)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS NOTES;
CREATE TABLE IF NOT EXISTS NOTES(
  id_note int(11) AUTO_INCREMENT,
  matiere VARCHAR(20),
  valeur int(11),
  id_etudiant int(11),
  PRIMARY KEY (id_note)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

